name: "[Nix] Build & Test"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: "[Nix] Flake Check, Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # To leverage devenv inside Github Actions
      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: "[Nix] Run treefmt to check Erlang / Gleam / Nix"
        run: |
          nix flake check

      - name: "[Nix] Build"
        run: |
          nix build
